### ISSUE TITLE
How install Dependencies from Pipfile ?

### ISSUE THREAD

**Issue by patsevanton** [thiiagoms/links-extractor#26]
Hello! Thanks for [links-extractor](https://github.com/thiiagoms/links-extractor)
How install Dependencies from Pipfile ?

**Comment by thiiagoms** [comment]
Hello @patsevanton, how are you ?! 

You can install with:

Install with `pipenv` manager 🐍 :

```shell
python3 -m venv .venv
source .venv/bin/activate
pip install pipenv
pipenv install
python example.py
```
Install with `docker` 🐳 :
```shell
docker build -t links-extractor .
docker run -it links-extractor:latest bash 
python example.py
```
